name: Build KernelSU Release
on:
  workflow_dispatch:
    inputs:
      localversion:
        description: vermagic suffix
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "HELLO"
